HAI
I HAS A BEBE
I HAS A VAR ITZ 5
I HAS A WINNER ITZ WIN
I HAS A thing ITZ WIN
I HAS A FLOAT ITZ 1.25
GIMMEH VAR
VAR R 7
BEBE R "POKPOK"
VISIBLE VAR
VISIBLE 5
VISIBLE "HELLO WORLD"
SUM OF SUM OF 1 AN 2 AN SUM OF 3 AN 4
SUM OF 10.5 AN SUM OF 20.5 AN 30.6
KTHXBYE