HAI
I HAS A x ITZ 5
I HAS A y ITZ 6
I HAS A answer
answer R SMALLR OF x AN y
VISIBLE "min(" x "," y ") is " answer
VISIBLE SUM OF x AN y
VISIBLE SUM OF 5 AN 6 
VISIBLE "HELLO WORLD I AM PROGRAMMER I LOVE PAKISTAN"
KTHXBYE